### ISSUE TITLE
Zip files are incompatible with Java's java.util.zip

### ISSUE THREAD

**Issue by sveniu** [64kramsystem/terraform-provider-archive-dev#1]
The zip files produced by this patch are causing incompatibility issues that don't seem to be very easy to work around.

```
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:311)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:123)
        at com.meh.test.UnzipFiles.unzip(UnzipFiles.java:30)
        at com.meh.test.UnzipFiles.main(UnzipFiles.java:17)
```

The combination of Go's streaming (i.e. writing ext data descriptors after each file entry) and use of STORE is not supported by Java.

More details: https://github.com/hashicorp/terraform-provider-archive/pull/47#pullrequestreview-506845964

**Comment by saveriomiroddi** [comment]
Hello!

Very interesting case (and thanks!).

Do you have a test case to reproduce it? I've been trying on my system, without success.

Java source:

```java
import java.io.File;
import java.io.IOException;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

public class unzip {
    public static void main(String[] args) throws IOException {
        String fileZip = "test.stor.zip";
        File destDir = new File("testdir");
        byte[] buffer = new byte[1024];
        ZipInputStream zis = new ZipInputStream(new FileInputStream(fileZip));
        ZipEntry zipEntry = zis.getNextEntry();
        while (zipEntry != null) {
            File newFile = newFile(destDir, zipEntry);
            FileOutputStream fos = new FileOutputStream(newFile);
            int len;
            while ((len = zis.read(buffer)) > 0) {
                fos.write(buffer, 0, len);
            }
            fos.close();
            zipEntry = zis.getNextEntry();
        }
        zis.closeEntry();
        zis.close();
    }

    public static File newFile(File destinationDir, ZipEntry zipEntry) throws IOException {
        File destFile = new File(destinationDir, zipEntry.getName());

        String destDirPath = destinationDir.getCanonicalPath();
        String destFilePath = destFile.getCanonicalPath();

        if (!destFilePath.startsWith(destDirPath + File.separator)) {
            throw new IOException("Entry is outside of the target dir: " + zipEntry.getName());
        }

        return destFile;
    }
}
```

Shell execution:

```
$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

$ echo -n > test.txt && rm -f test.stor.zip && zip -0 test.stor.zip test.txt
  adding: test.txt (stored 0%)

$ zipinfo -v test.stor.zip
Archive:  test.stor.zip
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                       166 (00000000000000A6h)
  Actual end-cent-dir record offset:           144 (0000000000000090h)
  Expected end-cent-dir record offset:         144 (0000000000000090h)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 1 entry.
  The central directory is 78 (000000000000004Eh) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 66 (0000000000000042h).


Central directory entry #1:
---------------------------

  test.txt

  offset of local header from start of archive:   0
                                                  (0000000000000000h) bytes
  file system or operating system of origin:      Unix
  version of encoding software:                   3.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   1.0
  compression method:                             none (stored)
  file security status:                           not encrypted
  extended local header:                          no
  file last modified on (DOS date/time):          2020 Oct 13 16:12:00
  file last modified on (UT extra field modtime): 2020 Oct 13 16:12:00 local
  file last modified on (UT extra field modtime): 2020 Oct 13 14:12:00 UTC
  32-bit CRC value (hex):                         00000000
  compressed size:                                0 bytes
  uncompressed size:                              0 bytes
  length of filename:                             8 characters
  length of extra field:                          24 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  Unix file attributes (100664 octal):            -rw-rw-r--
  MS-DOS file attributes (00 hex):                none

  The central-directory extra field contains:
  - A subfield with ID 0x5455 (universal time) and 5 data bytes.
    The local extra field has UTC/GMT modification/access times.
  - A subfield with ID 0x7875 (Unix UID/GID (any size)) and 11 data bytes:
    01 04 e8 03 00 00 04 e8 03 00 00.

  There is no file comment.

$ javac unzip.java && java unzip && rm testdir/test.txt
# succeeds!
```

**Comment by sveniu** [comment]
I put the test zip in https://github.com/aws/containers-roadmap/issues/1112, and just now edited it to include an unzip program and jre version info. It's at the bottom of the issue text.

**Comment by sveniu** [comment]
Oh, and the zip was produced by

```terraform
provider "archive" {
  # Use the patched provider.
  version = "1.2.0-4-g347a1af"
}

data "archive_file" "test" {
  type        = "zip"
  source_file = "${path.module}/src/test1.txt"
  output_path = "${path.module}/test.zip"

  normalize_files_metadata = true
}
```

**Comment by 64kramsystem** [comment]
@sveniu So! Many thanks for the plethora of information (and sorry for the late reply) :slightly_smiling_face: 

First of all, there is a working solution.

Now, there is a bigger picture discussion that needs to be taken into account.

First, regarding the solution itself, it's straightforward to integrate the [zipper](https://github.com/30x/zipper) library you've referenced. In the basic implementation, `terraform-provider-archive-dev` creates the zip files as it currently does, with a temporary filename, then process it and outputs in the final form.

Since the `zipper` processing logic works in memory, a second iteration could simply create the zip file in-memory, process it, and output it. In this case, I'd need to have a look at the APIs, since I'm not a Golang programmer, but my rough guess is that this shouldn't be a problem.

I didn't do extensive testing, but I've written a simple Golang compressor, with integrated the` zipper`, and tested both on the file you've provided and on another file, and the Java decompression works fine. Of course, I can't confirm this is stable without further tests.

Now, the discussion is ultimately about how to design/distribute the change.

Assuming that the patch is stable, it should decided if:

1. another flag should be used for this special processing,
2. if the normalization should always be processed.

I think option 2 is fine. I don't see any use case where a user would bother the flexibility given by option 1.

Regarding the distribution, we have freedom here. The TF provider maintainers (there's really no nicer way to put this) simply don't care about this PR, so there are no restrictions here - if you think the processing should be added to the plugin, I'll do it, test it, release it, etc. 

Thanks for the participation :slightly_smiling_face:

**Comment by 64kramsystem** [comment]
Source code of the program I've performed the tests with. Nothing special, just adding them for reference.

[unzip.java.txt](https://github.com/saveriomiroddi/terraform-provider-archive-dev/files/5520411/unzip.java.txt)
[zip.go.txt](https://github.com/saveriomiroddi/terraform-provider-archive-dev/files/5520412/zip.go.txt)

**Comment by 64kramsystem** [comment]
I'm bringing this to closure :)

In my previous reply, I've explained the solution (and tested it). I did not integrate because the maintainers are not showing interest in the topic.

This fork, and the related work, sit therefore in a strange place between a contribution for an upstream project, and an internal one. From the upstreaming perspective, any work is a waste, since it's factually not considered. From our internal tooling perspective, any work is also a waste, since everything works for us already (and TF development in not in our focus).

If the upstream project had interest, I'd certainly improve the PR, but this is not the case. Therefore, I've officially decided I'm done with any `terraform-provider-archive-dev`.

That said:

- I'm keeping this open for reference, in case somebody would like to understand the issue and the solution
- I thank you again for the information provided, that I indeed used for testing the problem and the solution :)
